// @ts-nocheck
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { describe, expect, it } from 'vitest'

const stylesDirectory = dirname(fileURLToPath(import.meta.url))
const baseStyles = readFileSync(join(stylesDirectory, 'styles.css'), 'utf8')
const detailStyles = readFileSync(join(stylesDirectory, 'styles/detail.css'), 'utf8')
const adminShellStyles = readFileSync(join(stylesDirectory, 'styles/admin-shell.css'), 'utf8')
const adminStyles = readFileSync(join(stylesDirectory, 'styles/admin.css'), 'utf8')
const styles = [baseStyles, detailStyles, adminShellStyles, adminStyles].join('\n')


describe('mobile latency target layout', () => {
  it('keeps latency targets in a separator grid without an outer perimeter', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(baseStyles).toMatch(/\.kulin-shell\s*\{[^}]*overflow-x: clip;[^}]*\}/)
    expect(styles).toContain('.latency-target-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0; margin: 0 12px; padding: 0; }')
    expect(styles).toMatch(/\.latency-target-grid\s*\{[^}]*margin: 0 24px;[^}]*border: 0;[^}]*\}/)
    expect(styles).toMatch(/\.latency-target-grid button\s*\{[^}]*margin: 0;[^}]*border: 0;[^}]*border-radius: 0;[^}]*\}/)
    expect(baseStyles).toMatch(/\.latency-target-grid button:not\(:nth-child\(7n \+ 1\)\)\s*\{[^}]*border-left: 1px solid/)
    expect(baseStyles).toMatch(/\.latency-target-grid button:nth-child\(n \+ 8\)\s*\{[^}]*border-top: 1px solid/)
    expect(baseStyles).toMatch(/@media \(max-width: 767px\)[\s\S]*?\.latency-target-grid button:not\(:nth-child\(7n \+ 1\)\) \{ border-left: 0; \}[\s\S]*?\.latency-target-grid button:nth-child\(n \+ 8\) \{ border-top: 0; \}[\s\S]*?\.latency-target-grid button:not\(:nth-child\(3n \+ 1\)\)[\s\S]*?border-left: 1px solid[\s\S]*?\.latency-target-grid button:nth-child\(n \+ 4\)[\s\S]*?border-top: 1px solid/)
    expect(baseStyles).not.toContain(".latency-target-grid button[data-active='true'] { border-color:")
    expect(baseStyles).not.toContain(".latency-target-grid button:hover:not([data-active='true']) { border-color:")
    expect(styles).toContain('.latency-target-grid.is-loading button')
    expect(styles).not.toContain("button[data-active='true'] .latency-target-color")
    expect(styles).toContain('.latency-panel-skeleton')
    expect(styles).toContain('.resource-chart-frame')
    expect(styles).toContain('grid-template-columns: 46px minmax(0, 1fr)')
    expect(styles).toContain('.latency-chart .axis-label { font-size: 10px; }')
  })
})

describe('mobile server detail layout', () => {
  it('stacks dense desktop detail facts into readable mobile rows', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.detail-hero__main { align-items: center; flex-direction: row; gap: 10px; }')
    expect(styles).toContain('.detail-fact-strip { grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 0; }')
    expect(styles).toContain('.detail-fact.is-wide { grid-column: 1 / -1; min-height: 54px; padding: 9px 11px; }')
    expect(styles).toContain('.detail-fact:not(.is-wide) { justify-content: flex-start; }')
    expect(styles).toContain('.detail-fact.is-adaptive > strong { width: 100%; flex: 1 1 auto; display: flex; align-items: center; }')
    expect(styles).toContain('.detail-fact.is-adaptive.is-multiline > strong { align-items: flex-start; }')
    expect(styles).toContain('.detail-fact:not(.is-wide) strong { overflow: visible; text-overflow: clip; white-space: normal; overflow-wrap: anywhere; }')
    expect(styles).toContain('.detail-fact--traffic .detail-traffic-values { flex-direction: column; align-items: flex-start; gap: 3px; white-space: normal; }')
    expect(styles).toContain('.monitor-heading { padding: 16px 14px 10px; flex-direction: row; align-items: flex-start; gap: 8px; }')
    expect(styles).toContain('.monitor-heading-actions { width: auto; flex: none; flex-wrap: nowrap; align-items: flex-start; justify-content: flex-end; margin-left: auto; }')
    expect(styles).toContain('.resource-history-header { padding: 16px 14px 10px; flex-direction: row; align-items: flex-start; gap: 8px; }')
    expect(styles).toContain('.resource-range-row { width: auto; flex: none; flex-wrap: nowrap; justify-content: flex-end; margin-left: auto; }')
  })
})

describe('route stylesheet boundaries', () => {
  it('keeps heavyweight admin workspace styles out of the public entry stylesheet', () => {
    expect(baseStyles).not.toContain('.admin-modal-backdrop')
    expect(baseStyles).not.toContain('.admin-server-sort-list')
    expect(adminShellStyles).toContain('.admin-login-card')
    expect(adminShellStyles).toContain('.admin-state-card')
    expect(adminShellStyles).not.toContain('.admin-modal-backdrop')
    expect(adminShellStyles).not.toContain('.admin-server-sort-list')
    expect(adminStyles).toContain('.admin-modal-backdrop')
    expect(adminStyles).toContain('.admin-server-sort-list')
    expect(adminStyles).not.toContain('.admin-login-card')
    expect(adminStyles).not.toContain('.admin-section-nav')
    expect(adminStyles).not.toContain('.admin-state-card')
    expect(adminStyles).toContain('@media (max-width: 767px)')
  })
})

describe('homepage and admin shell layout', () => {
  it('keeps homepage chrome and overview inside one shared card shell', () => {
    expect(styles).toContain('.home-top-card')
    expect(styles).toContain('.home-top-card .kulin-nav')
    expect(styles).toContain('.home-top-card .home-summary')
  })

  it('keeps route and admin workspace loading cards at one stable destination-aligned position', () => {
    expect(baseStyles).toContain('.route-state-container { display: flex; flex-direction: column; gap: 24px; }')
    expect(baseStyles).toMatch(/\.route-state-panel\s*\{[^}]*min-height: 180px;[^}]*display: flex;[^}]*flex-direction: column;[^}]*\}/)
    expect(baseStyles).toMatch(/\.route-state-card,\s*\.admin-state-card\s*\{[^}]*min-height: 96px;[^}]*margin-top: 18px;[^}]*display: flex;[^}]*gap: 10px;[^}]*padding: 18px 20px;[^}]*border: 0;[^}]*border-top: 1px solid[^}]*border-radius: 0;[^}]*background: transparent;[^}]*\}/)
    expect(adminShellStyles).toContain('.admin-state-card { min-height: 84px; margin-top: 18px; padding: 16px; }')
    expect(adminStyles).not.toContain('.admin-state-card')
  })

  it('keeps the theme menu above later homepage sections', () => {
    expect(styles).toMatch(/\.home-top-card \{[^}]*position: relative;[^}]*z-index: 20;[^}]*overflow: visible;/)
    expect(styles).toMatch(/\.theme-menu-popover \{[^}]*z-index: 80;/)
    expect(adminShellStyles).toMatch(/\.admin-chrome-card\s*\{[^}]*z-index: 30;[^}]*display: flex;[^}]*flex-direction: column;[^}]*\}/)
    expect(adminShellStyles).toMatch(/\.admin-content-card\s*\{[^}]*z-index: 10;[^}]*min-height: 360px;[^}]*padding: 20px;[^}]*\}/)
    expect(adminShellStyles).toMatch(/\.admin-chrome-card \.admin-toolbar\s*\{[^}]*margin-top: 0;[^}]*padding-top: 3px;[^}]*border-top: 1px solid var\(--border\);/)
    expect(adminShellStyles).toContain('.admin-chrome-card .admin-toolbar { justify-content: center; padding-top: 5px; padding-bottom: 2px; }')
  })

  it('keeps top controls transparent in desktop and touch interaction states', () => {
    expect(styles).toContain('@media (hover: hover) and (pointer: fine)')
    expect(styles).toContain('.nav-icon-button:hover:not(:disabled) { background: transparent; color: var(--blue); transform: none; box-shadow: none; }')
    expect(styles).toContain('.nav-icon-button:disabled { cursor: default; opacity: .45; }')
    expect(styles).not.toContain('.home-top-card .nav-icon-button')
    expect(baseStyles).toContain('.login-link:hover { background: transparent; color: var(--blue); box-shadow: none; transform: none; }')
    expect(adminShellStyles).toMatch(/@media \(max-width: 767px\) and \(hover: none\), \(max-width: 767px\) and \(pointer: coarse\)\s*\{[\s\S]*?\.admin-panel--login \.login-link:hover,[\s\S]*?\.admin-chrome-card \.login-link:focus:not\(:focus-visible\)\s*\{[^}]*background: transparent;[^}]*color: var\(--foreground\);[^}]*box-shadow: none;[^}]*transform: none;/)
  })

  it('keeps mobile homepage server cards aligned to the top card width', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.kulin-node-card { max-width: none; min-height: 0; height: auto; }')
  })

  it('fits dedicated mobile backgrounds without cropping them against long page content', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.kulin-shell[data-background=\'on\']::before')
    expect(styles).toContain('var(--zeno-mobile-background-image, var(--zeno-desktop-background-image, none))')
    expect(styles).toContain('background-size: var(--zeno-mobile-background-size, cover)')
    expect(styles).toContain('box-shadow: inset 0 0 0 100vmax var(--zeno-background-overlay-color)')
    expect(styles).toContain('background-attachment: scroll')
  })

  it('uses one unboxed desktop row and a no-scroll mobile two-column summary', () => {
    expect(styles).toContain('.home-summary__metric')
    expect(styles).toContain('.home-summary__metric--status')
    expect(styles).toContain('.home-summary__metric--cost')
    expect(styles).toContain('.home-summary__status-dot')
    expect(styles).toContain('.home-summary__metric-label')
    expect(styles).toContain('.home-summary__metric-value')
    expect(styles).toContain('.home-summary__metric--upload')
    expect(styles).toContain('.home-summary__metric--download')
    expect(styles).toMatch(/\.home-top-card \.home-summary\s*\{[^}]*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\);[^}]*padding: 12px 0 0;[^}]*border-top: 1px solid color-mix\(in srgb, var\(--border\) 82%, transparent\);[^}]*\}/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*border: 1px solid var\(--border\)/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*background:/)
    expect(styles).not.toMatch(/\.home-top-card \.home-summary\s*\{[^}]*border-radius:/)
    expect(styles).toMatch(/\.home-summary__metric\s*\{[^}]*min-height: 40px;[^}]*align-items: center;[^}]*justify-content: space-between;[^}]*gap: 6px;[^}]*padding: 0 16px;[^}]*font-size: 12px;[^}]*font-weight: 400;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric \+ \.home-summary__metric\s*\{\s*box-shadow: inset 1px 0 var\(--border\);\s*\}/)
    expect(styles).not.toContain('.home-summary__tile')
    expect(styles).toContain('--summary-accent')
    expect(styles).toMatch(/\.home-summary__metric-label\s*\{[^}]*justify-content: flex-start;[^}]*gap: 5px;[^}]*flex: none;[^}]*font-size: 11px;[^}]*font-weight: 400;[^}]*letter-spacing: \.01em;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value\s*\{[^}]*flex: 0 1 auto;[^}]*justify-content: flex-end;[^}]*gap: 3px;[^}]*margin-left: auto;[^}]*text-align: right;[^}]*white-space: nowrap;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value strong\s*\{[^}]*font-size: 13px;[^}]*font-weight: 500;[^}]*letter-spacing: -\.01em;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value > span\s*\{[^}]*font-size: 11px;[^}]*font-weight: 500;[^}]*\}/)
    expect(styles).toContain('.home-summary__metric--rate { gap: 6px; }')
    expect(styles).toContain('.home-summary__metric--rate > .home-summary__metric-label { width: auto; }')
    expect(styles).toMatch(/\.home-summary__metric-value--rate\s*\{[^}]*flex: 0 1 auto;[^}]*gap: 4px;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value--rate > strong\s*\{[^}]*width: auto;[^}]*text-align: right;[^}]*\}/)
    expect(styles).toMatch(/\.home-summary__metric-value--rate > span\s*\{[^}]*width: auto;[^}]*text-align: right;[^}]*\}/)
    expect(styles).toContain('.home-summary__metric-value--total strong { color: var(--summary-accent); }')
    expect(styles).not.toContain('.home-summary__metric-value--status strong')
    expect(styles).not.toContain('.home-summary__metric-value--cost strong')
    expect(styles).toContain('.home-currency-menu')
    expect(styles).toMatch(/\.home-currency-menu\s*\{[^}]*position: relative;[^}]*width: 52px;[^}]*height: 36px;[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-select\s*\{[^}]*display: inline-flex;[^}]*flex-wrap: nowrap;[^}]*justify-content: center;[^}]*white-space: nowrap;[^}]*\}/)
    expect(styles).not.toContain('.home-currency-select__flag')
    expect(styles).not.toContain('.home-currency-select svg')
    expect(styles).toMatch(/\.home-currency-select__value\s*\{[^}]*font-size: 14px;[^}]*font-weight: 500;[^}]*\}/)
    expect(styles).toContain('.home-currency-select:focus-visible')
    expect(styles).toContain('.home-currency-select[aria-expanded="true"]')
    expect(styles).toMatch(/\.home-currency-select\s*\{[^}]*transition:[^}]*transform 150ms ease;[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-select:hover,[\s\S]*?\.home-currency-select\[aria-expanded="true"\]\s*\{[^}]*background: transparent;[^}]*transform: none;[^}]*\}/)
    expect(styles).not.toContain('.home-currency-select select')
    expect(styles).toContain('.home-currency-popover')
    expect(styles).not.toContain('.home-currency-popover__title')
    expect(styles).toMatch(/\.home-currency-popover\s*\{[^}]*right: 0;[^}]*left: auto;[^}]*transform-origin: top right;[^}]*\}/)
    expect(styles).toContain('.home-currency-popover { left: 50%; right: auto; transform: translateX(-50%); transform-origin: top center; }')
    expect(styles).toContain('.home-currency-option__flag')
    expect(styles).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(styles).toContain('background: var(--zeno-popover-bg)')
    expect(styles).toContain('backdrop-filter: none')
    expect(styles).toContain('.home-currency-popover button[data-active="true"]')
    expect(styles).toContain('border: 1px solid var(--border)')
    expect(styles).toContain('--surface-strong: transparent')
    expect(styles).toContain('color-mix(in srgb, var(--blue) 48%, var(--border))')
    expect(styles).toMatch(/\.home-summary__metric-icon\s*\{[^}]*width: 13px;[^}]*height: 13px;[^}]*color: var\(--summary-accent, var\(--orange\)\);[^}]*\}/)
    expect(styles).toMatch(/\.node-head\s*\{[^}]*min-height: 24px;[^}]*grid-template-columns: 70px minmax\(0, 1fr\) 70px;[^}]*text-align: center;[^}]*\}/)
    expect(styles).toMatch(/\.node-os\s*\{[^}]*position: static;[^}]*grid-column: 1;[^}]*justify-self: start;[^}]*width: 20px;[^}]*height: 20px;[^}]*transform: none;[^}]*\}/)
    expect(styles).toMatch(/\.node-title-line\s*\{[^}]*grid-column: 2;[^}]*display: flex;[^}]*align-items: center;[^}]*justify-content: center;[^}]*gap: 4px;[^}]*\}/)
    expect(styles).toMatch(/\.node-uptime\s*\{[^}]*grid-column: 3;[^}]*justify-self: end;[^}]*color: var\(--green\);[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).not.toContain('.node-status-dot')
    expect(styles).not.toContain('.node-status.is-online')
    expect(styles).not.toContain('.node-status.is-offline')
    expect(styles).not.toContain('.node-title-line::after')
    expect(styles).not.toContain('.node-dot')
    expect(styles).not.toContain('.node-title-copy')
    expect(styles).not.toContain('.node-title-primary')
    expect(styles).not.toContain('.node-renewal-slot')
    expect(styles).not.toContain('.node-renewal-cost')
    expect(styles).not.toContain('.node-expiry-meta')
    expect(styles).toMatch(/\.node-specs\s*\{[^}]*margin-top: 14px;[^}]*grid-template-columns: repeat\(3, auto\);[^}]*justify-content: center;[^}]*gap: 0;[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).toContain('.node-spec + .node-spec { border-left: 1px solid')
    expect(styles).toMatch(/\.node-spec svg\s*\{[^}]*width: 16px;[^}]*height: 16px;[^}]*\}/)
    expect(styles).toContain('.spec-cpu svg { color: #0ea5e9; }')
    expect(styles).toContain('.spec-memory svg { color: #10b981; }')
    expect(styles).toContain('.spec-disk svg { color: #8b5cf6; }')
    expect(styles).toMatch(/\.node-usage-grid\s*\{[^}]*grid-template-columns: minmax\(0, 1fr\);[^}]*gap: 0;[^}]*\}/)
    expect(styles).toMatch(/\.usage-row\s*\{[^}]*display: flex;[^}]*gap: 6px;[^}]*padding: 6px 0;[^}]*\}/)
    expect(styles).toContain('.usage-row + .usage-row { border-top: 1px solid')
    expect(styles).toMatch(/\.usage-track\s*\{[^}]*height: 10px;[^}]*\}/)
    expect(styles).not.toContain('.usage-row__detail')
    expect(styles).not.toContain('.usage-row__icon')
    expect(styles).toContain('.usage-row--cpu { --resource-accent: var(--blue); }')
    expect(styles).toContain('.usage-row--memory { --resource-accent: var(--green); }')
    expect(styles).toContain('.usage-row--disk { --resource-accent: var(--purple); }')
    expect(styles).toContain('.usage-row--traffic { --resource-accent: var(--orange); }')
    expect(styles).toMatch(/\.node-footer-grid\s*\{[^}]*--node-footer-item-height: 36px;[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[^}]*gap: 0;[^}]*border-top: 1px solid var\(--border\);[^}]*\}/)
    expect(styles).toMatch(/\.node-metric\s*\{[^}]*min-height: var\(--node-footer-item-height\);[^}]*flex-direction: row;[^}]*justify-content: space-between;[^}]*gap: 4px;[^}]*border: 0;[^}]*background: transparent;[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).toContain('.node-metric:nth-child(even) { border-left: 1px solid var(--border); }')
    expect(styles).toContain('.node-metric:nth-child(n + 3) { border-top: 1px solid var(--border); }')
    expect(styles).toMatch(/\.server-card-list\s*\{[^}]*grid-auto-rows: auto;[^}]*align-items: start;[^}]*\}/)
    expect(styles).toMatch(/\.kulin-node-card\s*\{[^}]*min-height: 0;[^}]*height: auto;[^}]*\}/)

    // The billing metric holds the longest footer string (currency + amount +
    // a cycle like "五年"), so it must be able to claim the whole row when a
    // half row would ellipsise it. This is measured against the card, not the
    // viewport, because the same viewport yields different card widths at 2 vs
    // 3 columns -- a media query cannot express that.
    expect(styles).toMatch(/\.node-usage\s*\{[^}]*container-type: inline-size;[^}]*\}/)
    expect(styles).toMatch(/@container \(max-width: 285px\) \{\s*\.node-footer-grid \.node-metric\.metric-expiry,\s*\.node-footer-grid \.node-metric\.metric-billing \{[^}]*grid-column: 1 \/ -1;[^}]*border-left: 0;/)
    expect(styles).toMatch(/\.node-usage\s*\{[^}]*margin-top: 18px;[^}]*flex: none;[^}]*grid-template-rows: auto auto;[^}]*align-content: start;[^}]*gap: 14px;[^}]*\}/)
    expect(styles).not.toContain('.node-health-history')
    expect(styles).toContain('.node-footer-grid > .node-health-metric { grid-column: 1 / -1; }')
    expect(styles).toMatch(/\.node-health-metric\s*\{[^}]*min-height: var\(--node-footer-item-height\);[^}]*padding: 10px 8px;[^}]*border: 0;[^}]*border-top: 1px solid var\(--border\);[^}]*background: transparent;[^}]*font-size: 11px;[^}]*\}/)
    expect(styles).not.toContain('.node-health-metric + .node-health-metric')
    expect(styles).toMatch(/\.history-cell\s*\{[^}]*height: 12px;[^}]*\}/)
    expect(styles).toMatch(/\.health-history-strip\s*\{[^}]*grid-template-columns: repeat\(12, minmax\(0, 1fr\)\);[^}]*\}/)
    expect(styles).toContain('.history-cell.is-good')
    expect(styles).toContain('.history-cell.is-warning')
    expect(styles).toContain('.history-cell.is-danger')
    expect(styles).toContain('.history-cell.is-empty')
    expect(styles).toContain('--billing-gold: light-dark(#b8860b, #ffd45c);')
    expect(styles).toMatch(/\.metric-expiry\.is-safe\s*\{\s*--metric-accent: var\(--green\);\s*\}/)
    expect(styles).toMatch(/\.metric-expiry\.is-soon\s*\{\s*--metric-accent: var\(--orange\);\s*\}/)
    expect(styles).toMatch(/\.metric-expiry\.is-urgent,\s*\.metric-expiry\.is-expired\s*\{\s*--metric-accent: var\(--red\);\s*\}/)
    expect(styles).toContain('.metric-billing { --metric-accent: var(--billing-gold); }')
    expect(styles).toMatch(/\.home-summary__status-dot\s*\{[^}]*width: 6px;[^}]*height: 6px;[^}]*background: var\(--green\);[^}]*\}/)
    expect(styles).toMatch(/\.home-top-card \.home-summary\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[^}]*row-gap: 2px;[^}]*padding-top: 10px;[^}]*overflow: hidden;[^}]*\}/)
    expect(styles).not.toContain('.home-top-card .home-summary::-webkit-scrollbar')
    expect(styles).toContain('.home-summary__metric + .home-summary__metric { box-shadow: none; }')
    expect(styles).toContain('.home-summary__metric:nth-child(2n) { box-shadow: inset 1px 0 var(--border); }')
    expect(styles).toContain('.home-summary__metric:nth-child(n + 3) { box-shadow: inset 0 1px var(--border); }')
    expect(styles).toContain('.home-summary__metric:nth-child(2n):nth-child(n + 3) { box-shadow: inset 1px 0 var(--border), inset 0 1px var(--border); }')
    expect(styles).toMatch(/\.home-summary__metric\s*\{\s*min-height: 34px; gap: 5px; padding: 0 12px;\s*\}/)
    expect(styles).toContain('.home-summary__metric--rate { gap: 5px; }')
    expect(styles).toContain('.home-summary__metric--rate > .home-summary__metric-label { width: calc(2em + 16px); }')
    expect(styles).toContain('.home-summary__metric-value--rate { gap: 4px; }')
    expect(styles).toContain('@media (max-width: 360px)')
    expect(styles).toContain('.home-summary__metric { gap: 3px; padding: 0 6px; font-size: 11px; }')
    expect(styles).toContain('.home-summary__metric-label { gap: 3px; font-size: 10px; }')
    expect(styles).toContain('.home-summary__metric-value strong { font-size: 12px; }')
    expect(styles).toContain('.home-summary__metric-value > span { font-size: 10px; }')
    expect(styles).toContain('.home-summary__metric--rate { gap: 4px; padding-inline: 3px; }')
    expect(styles).toContain('.home-summary__metric--rate > .home-summary__metric-label { width: calc(2em + 13px); }')
    expect(styles).toContain('.home-summary__metric--rate .home-summary__metric-value { gap: 3px; }')
    expect(styles).toContain('.home-currency-menu { width: 50px; height: 32px; flex-basis: 50px; }')
    expect(styles).toContain('.home-currency-select__value { font-size: 12px; font-weight: 500; }')
    expect(styles).not.toContain('.home-summary__status-body')
    expect(styles).not.toContain('.home-summary__status-cost')
    expect(styles).not.toContain('.home-summary__snapshot')
    expect(styles).not.toContain('.home-summary__network-board')
    expect(styles).not.toContain('.home-summary__status-track')
    expect(styles).not.toContain('--gold:')
    expect(styles).toContain('font-weight: 400')
    expect(styles).not.toContain('.home-summary__compact')
  })

  it('keeps the theme menu aligned with the active card theme while utility popovers stay opaque', () => {
    expect(styles).toContain(':root[data-zeno-theme="light"]')
    expect(styles).toContain(':root[data-zeno-theme="dark"]')
    expect(styles).toMatch(/:root\[data-zeno-theme="light"\]\s*\{[^}]*color-scheme: light;/)
    expect(styles).toMatch(/:root\[data-zeno-theme="dark"\]\s*\{[^}]*color-scheme: dark;/)
    expect(styles).toContain('--zeno-popover-bg: light-dark(rgb(255, 255, 255), rgb(15, 23, 42))')
    expect(baseStyles).toMatch(/\.theme-menu-popover\s*\{[^}]*background: var\(--page-surface\);[^}]*color: var\(--foreground\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.theme-menu-popover\s*\{[^}]*box-shadow: var\(--zeno-card-shadow\);[^}]*backdrop-filter: blur\(var\(--zeno-card-blur\)\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.theme-menu-popover\.is-gaussian\s*\{[^}]*background: color-mix\(in srgb, var\(--page-surface\) 30%, transparent\);[^}]*\}/)
    expect(styles).not.toContain('--zeno-popover-blur')
    expect(baseStyles).toMatch(/\.admin-select-popover,\s*\.admin-install-platforms\s*\{[^}]*background: var\(--zeno-popover-bg\);[^}]*backdrop-filter: none;[^}]*\}/)
    expect(styles).toMatch(/\.home-currency-popover\s*\{[^}]*background: var\(--zeno-popover-bg\);[^}]*backdrop-filter: none;[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-select-popover,\s*\.admin-install-platforms\s*\{[^}]*background: var\(--admin-secondary-surface\);[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-date-popover\s*\{[^}]*background: var\(--admin-secondary-surface\);[^}]*backdrop-filter: none;[^}]*\}/)
    expect(styles).toMatch(/\.admin-date-option-panel\s*\{[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(styles).toMatch(/\.admin-expanded-checklist__panel\s*\{[^}]*border-top: 1px solid var\(--border\);[^}]*background: transparent;[^}]*\}/)
    expect(styles).toMatch(/\.admin-expanded-checklist__list\s*\{[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
  })

  it('enforces the whole-app single-surface allowlist', () => {
    for (const variable of ['--surface-strong', '--surface', '--surface-soft', '--secondary', '--metric-bg', '--field-bg', '--control-bg']) {
      expect(baseStyles).toContain(`${variable}: transparent`)
    }
    expect(baseStyles).toMatch(/\.home-top-card\s*\{[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.admin-modal\s*\{[^}]*backdrop-filter: blur\(var\(--zeno-card-blur\)\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card,\s*\.region-filter-bar,\s*\.state-panel,\s*\.kulin-node-card,\s*\.monitor-panel\s*\{[^}]*position: relative;[^}]*isolation: isolate;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.kulin-node-card\s*\{[^}]*background: transparent;[^}]*\}/)
    expect(detailStyles).toMatch(/\.monitor-panel\s*\{[^}]*background: transparent;[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card::before,\s*\.region-filter-bar::before,\s*\.state-panel::before,\s*\.kulin-node-card::before,\s*\.monitor-panel::before\s*\{[^}]*inset: -128px;[^}]*background-color: transparent;[^}]*background-image: var\(--zeno-desktop-background-image, none\);[^}]*background-attachment: fixed;[^}]*filter: blur\(var\(--zeno-card-blur\)\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card::before\s*\{[^}]*clip-path: inset\(128px round var\(--radius-panel\)\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card::after,\s*\.region-filter-bar::after,\s*\.state-panel::after,\s*\.kulin-node-card::after,\s*\.monitor-panel::after\s*\{[^}]*inset: 0;[^}]*border-radius: inherit;[^}]*background: var\(--page-surface\);[^}]*\}/)
    expect(baseStyles).toMatch(/@media \(max-width: 767px\)[\s\S]*?\.kulin-shell\[data-background='on'\]::before\s*\{[^}]*background-image: var\(--zeno-mobile-background-image, var\(--zeno-desktop-background-image, none\)\);[^}]*filter: blur\(var\(--zeno-card-blur\)\);[^}]*transform: scale\(1\.06\);[^}]*\}/)
    expect(baseStyles).not.toContain('mobile-gaussian-layer')
    expect(baseStyles).not.toContain('--zeno-mobile-glass-mask')
    expect(baseStyles).toMatch(/@media \(max-width: 767px\)[\s\S]*?\.home-top-card::before,[\s\S]*?\.monitor-panel::before\s*\{[^}]*content: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.region-filter-bar\s*\{[^}]*overflow: hidden;[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.state-panel\s*\{[^}]*overflow: hidden;[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.state-panel button\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).not.toContain('.monitor-panel,\n.admin-login-card,')
    expect(baseStyles).not.toContain('.admin-login-card,\n.admin-state-card,')
    expect(adminShellStyles).toMatch(/\.admin-login-card\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector\s*\{[^}]*background: transparent;[^}]*\}/)
    expect(adminShellStyles).not.toMatch(/(^|\n)\.admin-section-nav\s*\{/)
    expect(adminStyles).toMatch(/\.admin-appearance-preview__card\s*\{[^}]*background: transparent;[^}]*backdrop-filter: none;[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-modal-backdrop\s*\{[^}]*backdrop-filter: none;[^}]*\}/)
  })

  it('keeps the backend on the same outer-surface-only glass policy as the front page', () => {
    expect(styles).toContain('.admin-panel')
    expect(styles).toContain('.admin-workspace-panel .admin-list')
    expect(styles).toContain('--surface-strong')
    expect(styles).toContain('--surface-strong: transparent')
    expect(styles).toContain('--zeno-card-blur')
    expect(styles).toContain('backdrop-filter: blur(var(--zeno-card-blur))')
    expect(adminShellStyles).toMatch(/\.admin-login-card\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).not.toContain('.monitor-panel,\n.admin-login-card,')
    expect(styles).not.toContain('saturate(1.14)')
  })

  it('keeps the homepage backend entry visible on phones', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.login-link {')
    expect(styles).not.toContain('.nav-logout-button')
    expect(styles).toContain('min-height: 32px')
    expect(styles).not.toContain('.login-link { display: none; }')
  })

  it('keeps backend mobile navigation and every secondary action footer in the content plane', () => {
    expect(styles).toContain('@media (max-width: 767px)')
    expect(styles).toContain('.admin-section-nav button {')
    expect(adminShellStyles).toContain('.admin-chrome-card .admin-section-nav')
    expect(adminShellStyles).toContain('grid-template-columns: repeat(var(--slider-columns), minmax(0, 1fr))')
    expect(styles).toContain('overflow: hidden')
    expect(styles).toContain('.admin-chrome-card .admin-section-nav {')
    expect(styles).toContain('grid-template-columns: repeat(var(--slider-columns), minmax(0, 1fr))')
    expect(styles).toContain('.admin-chrome-card .admin-section-nav button { height: 24px; padding: 0 2px; }')
    expect(styles).not.toContain('.admin-chrome-card .admin-section-nav button:last-child')
    expect(styles).not.toContain('.admin-section-icon')
    expect(styles).not.toContain('scroll-snap-type: x proximity')
    expect(styles).toContain('.admin-modal { width: 100%; height: min(92dvh, 760px); max-height: calc(100dvh - 16px); border-radius: var(--radius-panel); padding: 0; }')
    const actionFooterRules = [...adminStyles.matchAll(/\.admin-action-footer\s*\{([^}]*)\}/g)].map((match) => match[1])
    expect(actionFooterRules.length).toBeGreaterThanOrEqual(2)
    expect(actionFooterRules[0]).toContain('position: static')
    expect(actionFooterRules[0]).toContain('z-index: auto')
    expect(actionFooterRules[0]).toContain('background: transparent')
    expect(actionFooterRules[0]).toContain('box-shadow: none')
    expect(actionFooterRules[0]).toContain('backdrop-filter: none')
    expect(actionFooterRules.join('\n')).not.toContain('position: sticky')
    expect(actionFooterRules.join('\n')).not.toContain('bottom: 0')
    expect(actionFooterRules.join('\n')).not.toContain('backdrop-filter: blur')
    expect(styles).toContain('margin: 16px 0 0')
    expect(styles).toContain('max(10px, env(safe-area-inset-bottom))')
    expect(styles).toContain('.admin-alert-rule-add-form .admin-rule-picker { margin-top: 0; }')
    expect(styles).toContain('.admin-node-edit-form button.admin-primary-action')
    expect(styles).toContain('.admin-section-heading h3 { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 21px; }')
    expect(styles).toContain('.admin-section-actions { width: auto; flex: 0 0 auto; margin-left: auto; justify-content: flex-end; flex-wrap: nowrap; gap: 6px; }')
    expect(styles).toContain('.admin-block-heading .admin-primary-action { height: 34px; padding: 0 10px; font-size: 12px; }')
    expect(styles).toContain('.admin-target-assignment-list,')
    expect(styles).toContain('.admin-notification-list .admin-row-actions.admin-icon-actions,')
  })

  it('keeps destructive confirmations compact, stable, and touch-friendly', () => {
    expect(styles).toContain('.admin-modal.admin-delete-modal')
    expect(styles).toContain('width: min(480px, 100%)')
    expect(styles).toContain('.admin-delete-confirm__lead')
    expect(styles).toContain('.admin-delete-confirm__hint')
    expect(styles).not.toContain('.admin-delete-subject')
    expect(styles).not.toContain('.admin-delete-impact')
    expect(styles).toContain('.admin-delete-feedback')
    expect(styles).toContain('min-height: 38px')
    expect(styles).toContain('max-height: 72px')
    expect(styles).toContain('.admin-delete-feedback.is-error')
    expect(styles).toContain('.admin-modal.admin-delete-modal { height: auto; max-height: calc(100dvh - 16px); }')
    expect(styles).toContain('.admin-delete-modal .admin-modal-close { width: 44px; height: 44px; flex: 0 0 44px; }')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 1.15fr)')
    expect(styles).toContain('min-height: 46px')
  })

  it('keeps authenticated node management in compact lists without old card shells', () => {
    expect(styles).toContain('.admin-login-card')
    expect(styles).toContain('width: min(100%, 440px)')
    expect(styles).toContain('grid-template-columns: 1fr')
    expect(styles).toContain('.admin-login-title { padding-bottom: 2px; text-align: center; }')
    expect(styles).toContain('.brand-logo-fallback')
    expect(styles).toContain('border-radius: 50%')
    expect(styles).toContain('gap: 20px')
    expect(styles).toContain('padding: 26px 24px')
    expect(styles).not.toContain('grid-template-columns: minmax(0, 1fr) minmax(140px, 220px)')
    expect(styles).toContain('.admin-node-section')
    expect(adminStyles).toMatch(/\.admin-node-section,[\s\S]*?\.admin-settings-section\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-list\s*\{[^}]*background: transparent;[^}]*\}/)
    expect(adminStyles).toContain('.admin-list-row:hover { position: relative; z-index: 1; background: transparent;')
    expect(styles).toContain(".admin-section-nav button[data-active='true']")
    expect(styles).toContain('.admin-node-status')
    expect(styles).toContain('.admin-status-indicator.status-online .admin-status-dot')
    expect(styles).toContain('.admin-server-sort-list')
    expect(styles).toContain('.admin-server-sort-item')
    expect(styles).toContain('cursor: grab')
    expect(styles).not.toContain('.admin-node-card')
    expect(styles).not.toContain('.admin-target-card')
    expect(styles).not.toContain('.admin-node-grid')
  })

  it('lets admin lists size to content without internal scroll containers', () => {
    expect(styles).toContain('.admin-workspace-panel .admin-list')
    expect(styles).toContain('max-height: none')
    expect(styles).toContain('overflow: visible')
    expect(styles).toContain('scrollbar-gutter: auto')
    expect(styles).toContain('padding: 10px 12px')
    expect(styles).toContain('min-height: 64px')
    expect(styles).toContain('.admin-ip-stack')
    expect(styles).toContain('height: 34px')
    expect(styles).toContain('repeat(auto-fit, minmax(96px, 1fr))')
    expect(styles).toContain('.admin-node-section .admin-list-row,')
    expect(styles).toContain('.admin-target-list .admin-list-row,')
    expect(styles).toContain('overflow-wrap: anywhere')
    expect(styles).not.toContain('max-height: calc(100dvh - 300px)')
    expect(styles).not.toContain('max-height: calc(100dvh - 260px)')
    expect(styles).not.toContain('.overview-card')
    expect(styles).not.toContain('.server-overview')
  })

  it('simplifies backend chrome and gives secondary forms card-aligned sections', () => {
    expect(styles).toContain('background: transparent')
    expect(styles).toContain('box-shadow: none')
    expect(styles).toContain('font-size: 23px')
    expect(styles).toContain('font-size: 15px')
    expect(styles).toContain('.admin-account-section,')
    expect(styles).toContain('.admin-form-section')
    expect(styles).toContain('.admin-form-section-title::before')
    expect(styles).toContain('border-radius: var(--radius-card)')
    expect(styles).not.toContain('.admin-segmented-options')
    expect(adminStyles).toMatch(/\.admin-select-popover,\s*\.admin-install-platforms\s*\{[^}]*border-radius: var\(--radius-card\);[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-select-popover\s*\{[^}]*overflow: auto;[^}]*clip-path: inset\(0 round var\(--radius-card\)\);[^}]*\}/)
    expect(styles).toContain('.admin-modal-body')
    expect(styles).toContain('clip-path: inset(0 round var(--radius-panel))')
    expect(styles).not.toContain('--admin-modal-section-bg')
    expect(styles).not.toContain('--admin-modal-control-bg')
    expect(styles).not.toContain('--admin-modal-action-bg')
    expect(styles).toContain('--admin-secondary-surface: light-dark(#ffffff, rgb(15, 23, 42))')
    expect(styles).toMatch(/\.admin-modal\s*\{[^}]*--surface-strong: transparent;[^}]*--field-bg: transparent;[^}]*--control-bg: transparent;[^}]*background: var\(--page-surface\);[^}]*\}/)
    expect(styles).toMatch(/\.admin-form-section\s*\{[^}]*background: transparent;[^}]*\}/)
    expect(adminStyles).toMatch(/\.admin-node-edit-form\s*\{[^}]*--surface-soft: transparent;[^}]*--field-bg: transparent;[^}]*--control-bg: transparent;[^}]*\}/)
    expect(baseStyles).not.toMatch(/\.admin-list,\s*\n\.admin-form-section,/)
    expect(baseStyles).toMatch(/\.home-top-card\s*\{[^}]*backdrop-filter: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card::before,[\s\S]*?\.monitor-panel::before\s*\{[^}]*filter: blur\(var\(--zeno-card-blur\)\);/)
    expect(baseStyles).toMatch(/\.admin-modal\s*\{[^}]*backdrop-filter: blur\(var\(--zeno-card-blur\)\);[^}]*\}/)
    const modalBackdropRule = adminStyles.match(/\.admin-modal-backdrop\s*\{([^}]*)\}/)?.[1] ?? ''
    expect(modalBackdropRule).toContain('background: rgba(15, 23, 42, .1)')
    expect(modalBackdropRule).toContain('backdrop-filter: none')
    expect(styles).toMatch(/\.admin-node-edit-form input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\),[\s\S]*?background: var\(--field-bg\);/)
    expect(adminStyles).toMatch(/\.admin-list-row\s*\{[^}]*position: relative;[^}]*border: 0;[^}]*border-bottom: 1px solid[^}]*border-radius: 0;[^}]*background: transparent;[^}]*\}/)
    expect(styles).toContain('.admin-notification-list .admin-node-status')
    expect(styles).toContain('.admin-install-copy-menu')
    expect(styles).toContain('.admin-install-copy-button')
    expect(styles).toContain('.admin-install-copy-row { flex-wrap: nowrap; gap: 10px; }')
    expect(styles).toContain('.admin-inline-note')
    expect(styles).toMatch(/\.admin-install-platforms\s*\{[^}]*position: fixed;/)
    expect(styles).not.toContain('scroll-margin: 96px 0')
    expect(styles).not.toContain('.admin-install-command')
  })
})

describe('state history layout', () => {
  it('keeps the detail hero dense with Nezha-like inline facts, not nested metric cards', () => {
    expect(styles).toContain('.detail-fact-strip')
    expect(styles).toContain('.detail-status-pill')
    expect(styles).toContain('.detail-fact.is-wide')
    expect(styles).not.toContain('.detail-fact.is-emphasis')
    expect(detailStyles).not.toContain('--detail-inner-surface')
    expect(detailStyles).toMatch(/\.detail-hero\s*\{[^}]*border: 0;[^}]*border-top: 1px solid color-mix\(in srgb, var\(--border\) 82%, transparent\);[^}]*border-radius: 0;[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-title-button\s*\{[^}]*min-height: 24px;[^}]*align-items: center;[^}]*line-height: 24px;[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-title-flag\s*\{[^}]*width: 24px;[^}]*height: 24px;[^}]*flex: 0 0 24px;[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-title-button > span:last-child\s*\{[^}]*min-height: 24px;[^}]*display: flex;[^}]*align-items: center;[^}]*line-height: 24px;[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-fact-strip\s*\{[^}]*border: 0;[^}]*border-top: 1px solid[^}]*border-radius: 0;[^}]*\}/)
    expect(detailStyles).toContain('.detail-fact-strip--server { border-top: 0; }')
    expect(detailStyles).toContain('.detail-top-card .kulin-nav { padding: 0 0 9px; }')
    expect(detailStyles).toMatch(/\.detail-fact\s*\{[^}]*border: 0;[^}]*border-radius: 0;[^}]*background: transparent;[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-fact-strip--server \.detail-fact:nth-child\(n \+ 3\)\s*\{[^}]*border-top: 1px solid/)
    expect(baseStyles).toMatch(/\.sliding-selector\s*\{[^}]*border: 1px solid var\(--border\);[^}]*background: transparent;[^}]*-webkit-tap-highlight-color: transparent;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector::before\s*\{[^}]*top: 0;[^}]*bottom: 0;[^}]*left: 0;[^}]*border-radius: calc\(var\(--radius-field\) - 1px\);[^}]*background: var\(--blue\);[^}]*transform: translateX\(var\(--slider-shift\)\);[^}]*\}/)
    expect(baseStyles).not.toMatch(/\.nav-icon-button\.is-solid\s*\{[^}]*border-color:/)
    expect(detailStyles).not.toMatch(/\.detail-top-card \.nav-icon-button\.is-solid\s*\{[^}]*border-color:/)
    expect(styles).toContain('.resource-history-header h3 { margin: 0; color: var(--foreground); font-size: 20px; font-weight: 600; }')
    expect(styles).toContain('border-top: 1px solid color-mix(in srgb, var(--border) 82%, transparent)')
    expect(styles).not.toContain('.detail-hero,\n.latency-panel,')
    expect(styles).not.toContain('.detail-info-card')
  })

  it('keeps every detail-page control and nested card on the outer single blur layer', () => {
    expect(baseStyles).toMatch(/\.nav-icon-button\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.login-link\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.theme-menu-popover\s*\{[^}]*border: 1px solid var\(--border\);[^}]*background: var\(--page-surface\);[^}]*color: var\(--foreground\);[^}]*\}/)
    expect(detailStyles).toMatch(/\.detail-status-pill\s*\{[^}]*border: 1px solid currentColor;[^}]*background: transparent;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector > button\s*\{[^}]*-webkit-appearance: none;[^}]*appearance: none;[^}]*touch-action: manipulation;[^}]*-webkit-tap-highlight-color: transparent;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector > button\.is-active,[\s\S]*?\.sliding-selector > button\[data-active='true'\]\s*\{[^}]*background: transparent;[^}]*color: #fff;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector > button:active\s*\{[^}]*background: transparent;[^}]*transform: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.sliding-selector > button:focus-visible\s*\{[^}]*border-radius: calc\(var\(--radius-field\) - 1px\);[^}]*outline: none;[^}]*box-shadow: inset 0 0 0 2px/)
    expect(detailStyles).not.toContain('button.is-active {\n  background: transparent;\n  color: #fff;\n  border-color: transparent;')
    expect(detailStyles).toMatch(/\.peak-switch span\s*\{[^}]*border: 1px solid var\(--border\);[^}]*background: transparent;[^}]*\}/)
    expect(baseStyles).toMatch(/\.latency-target-grid button\[data-active='true'\]\s*\{[^}]*background: color-mix\(in srgb, var\(--blue\) 12%, transparent\);[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.theme-menu-popover button\[data-active='true'\]\s*\{[^}]*background: color-mix\(in srgb, var\(--blue\) 12%, transparent\);[^}]*\}/)
    expect(adminShellStyles).toMatch(/\.admin-section-nav button\[data-active='true'\]\s*\{[^}]*background: transparent;[^}]*color: #fff;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.latency-tooltip-card\s*\{[^}]*background: color-mix\(in srgb, var\(--page-surface\) 82%, transparent\);[^}]*backdrop-filter: blur\(14px\) saturate\(1\.08\);[^}]*\}/)
    expect(baseStyles).toMatch(/\.resource-chart-tooltip\s*\{[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toMatch(/\.home-top-card,\s*\.region-filter-bar,\s*\.state-panel,\s*\.kulin-node-card,\s*\.monitor-panel\s*\{[^}]*backdrop-filter: none;/)
    expect(baseStyles).toMatch(/\.home-top-card::before,[\s\S]*?\.monitor-panel::before\s*\{[^}]*filter: blur\(var\(--zeno-card-blur\)\);/)
    expect(baseStyles).toMatch(/\.home-top-card::after,[\s\S]*?\.monitor-panel::after\s*\{[^}]*background: var\(--page-surface\);/)
    expect(baseStyles).not.toContain('.monitor-panel,\n.latency-panel,')
    expect(baseStyles).not.toContain('.latency-panel,\n.resource-card,')
  })

  it('renders resource history as a compact chart grid like Kulin on desktop', () => {
    expect(styles).toContain('.resource-history-grid')
    expect(styles).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(styles).toContain('grid-template-columns: 1fr')
    expect(styles).toContain('.resource-card')
    expect(baseStyles).toMatch(/\.resource-card\s*\{[^}]*border: 0;[^}]*border-radius: 0;[^}]*background: transparent;[^}]*box-shadow: none;[^}]*\}/)
    expect(baseStyles).toContain('.resource-card + .resource-card')
    expect(baseStyles).toContain('.resource-card:not(:nth-child(3n + 1))')
    expect(styles).toContain('.resource-y-axis')
    expect(styles).toContain('.resource-chart-plot')
    expect(styles).toContain('.resource-x-axis')
    expect(styles).toContain('.resource-chart-area { opacity: .2; stroke: none; pointer-events: none; }')
    expect(styles).toContain('.resource-card-header')
    expect(styles).toContain('grid-template-columns: minmax(0, 1fr) auto')
  })

  it('keeps only the server status as a compact pill in the top server card', () => {
    expect(styles).toContain('.detail-hero__badges')
    expect(styles).toContain('border-radius: var(--radius-pill)')
  })

  it('renders stationary Gaussian cards from an overscanned background image, not backdrop-filter', () => {
    expect(baseStyles).toContain('.kulin-node-card:hover { transform: none;')
    expect(baseStyles).not.toContain('transition: transform 160ms ease')
    expect(baseStyles).not.toContain(".kulin-shell[data-background='on'] .kulin-node-card:hover")
    expect(baseStyles).toMatch(/\.home-top-card,\s*\.region-filter-bar,\s*\.state-panel,\s*\.kulin-node-card,\s*\.monitor-panel\s*\{[^}]*backdrop-filter: none;/)
    expect(baseStyles).toMatch(/\.home-top-card::before,[\s\S]*?\.monitor-panel::before\s*\{[^}]*inset: -128px;[^}]*background-color: transparent;[^}]*background-attachment: fixed;[^}]*filter: blur\(var\(--zeno-card-blur\)\);/)
    expect(baseStyles).toMatch(/\.home-top-card::after,[\s\S]*?\.monitor-panel::after\s*\{[^}]*background: var\(--page-surface\);/)
  })

  it('freezes offline homepage cards by dimming colored content without grayscale', () => {
    expect(styles).toMatch(/\.kulin-node-card\.is-offline \.node-head,[\s\S]*?\.node-usage \{[^}]*opacity: \.56;[^}]*\}/)
    expect(styles).toMatch(/\.node-offline-watermark\s*\{[^}]*position: absolute;[^}]*z-index: 2;[^}]*pointer-events: none;[^}]*transform: rotate\(-24deg\);[^}]*color: color-mix\(in srgb, var\(--red\) 24%, transparent\);[^}]*font-size: 52px;[^}]*\}/)
    // Offline cards must never grayscale or tint the card surface (2026-07-05 decision).
    expect(styles).not.toContain('filter: grayscale')
    expect(styles).not.toMatch(/\.kulin-node-card\.is-offline\s*\{/)
    expect(styles).not.toContain('.kulin-node-card.is-offline::before')
  })

  it('keeps server-card usage tracks visible on white cards', () => {
    expect(styles).toContain('--usage-track-bg')
    expect(styles).toContain('--usage-track-border')
    expect(styles).toContain('background: var(--usage-track-bg)')
    expect(styles).toContain('.usage-track { position: relative; width: 100%; height: 10px; overflow: hidden; border: 0;')
  })
})

describe('Kulin-inspired color polish', () => {
  it('keeps a quiet grey canvas with solid white page surfaces instead of aurora backgrounds', () => {
    expect(styles).toContain('--background: light-dark(#f5f6f8, #07111f)')
    expect(styles).toContain('--page-surface: light-dark(#ffffff, #0f172a)')
    expect(styles).not.toContain('--card:')
    expect(styles).toContain('background-image: var(--zeno-desktop-background-image, none)')
    expect(styles).not.toContain('--zeno-glow-primary')
    expect(styles).not.toContain('radial-gradient(circle at')
    expect(styles).not.toContain('linear-gradient(135deg, var(--zeno-bg-a)')
  })

  it('uses solid accent colors without gradients and keeps key identity emphasized', () => {
    expect(styles).toContain('.home-summary__metric-value strong')
    expect(styles).toContain('.home-summary__metric-value > span')
    expect(styles).toContain('.home-summary__metric-value--rate > span')
    expect(styles).toContain('.metric-label { min-width: 0; overflow: hidden; color: var(--metric-accent)')
    expect(styles).toContain('.node-title-line p { max-width: calc(100% - 23px); min-width: 0; flex: none; margin: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--foreground); font-size: 13px; font-weight: 600')
    expect(styles).toContain('.detail-title-button > span:last-child { min-height: 24px; display: flex; align-items: center; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 600; line-height: 24px; }')
    expect(styles).toContain('.node-metric strong')
    expect(styles).toContain('.node-metric strong { max-width: 100%; min-width: 0; flex: 1; overflow: hidden; color: var(--metric-accent); font-size: 11px; font-weight: 500; line-height: 1.15; text-align: right; text-overflow: ellipsis; white-space: nowrap;')
    expect(styles).toContain('.metric-billing { --metric-accent: var(--billing-gold); }')
    expect(styles).toContain('.node-health-metric {')
    expect(styles).toContain('--metric-accent: var(--green);')
    expect(styles).toContain('.node-health-metric.health-loss { --metric-accent: var(--orange); }')
    expect(styles).not.toContain('.metric-latency')
    expect(styles).toContain('.latency-target-grid strong { color: var(--foreground); font-size: 20px')
    expect(styles).toContain('.detail-traffic-values { display: flex; align-items: center; column-gap: 18px; }')
    expect(styles).toContain('.detail-traffic-value { display: inline-flex; align-items: center; gap: 5px; min-width: 0; }')
    expect(styles).toContain('font-weight: 600; letter-spacing: -0.03em')
    expect(styles).toContain('.latency-monitor-heading .monitor-title-row h3 { font-weight: 600; }')
    expect(styles).toContain('.home-summary__metric-value--total strong')
    expect(styles).toContain('font-size: 13px')
    expect(styles).toContain('font-weight: 500')
    expect(styles.match(/font-weight: 600/g)?.length ?? 0).toBeGreaterThanOrEqual(4)
    expect(styles).toContain('.latency-target-grid em { color: var(--muted)')
    expect(styles).toContain('.admin-section-nav button[data-active=\'true\']')
    expect(styles).not.toContain('.admin-section-icon')
    expect(styles).toContain('background: var(--blue)')
    expect(styles).toContain('.resource-card.tone-green')
    expect(styles).toContain('.resource-chart-tooltip')
    expect(styles).toContain('.server-flag__image')
    expect(styles).toMatch(/\.region-filter-buttons\s*\{[^}]*width: fit-content;[^}]*grid-template-columns: repeat\(var\(--slider-columns\), 42px\);[^}]*border: 0;[^}]*\}/)
    expect(styles).toMatch(/\.region-filter-buttons \.server-flag \{[^}]*font-size: 16px;[^}]*\}/)
    expect(styles).not.toMatch(/\.region-filter-buttons \.server-flag \{[^}]*(?:border|box-shadow|overflow)[^}]*\}/)
    expect(styles).toContain('.latency-chart-tooltip foreignObject')
    expect(styles).toContain('.latency-tooltip-card')
    expect(styles).not.toContain('<title>')
    expect(styles).not.toContain('.resource-card::before')
    expect(styles).not.toContain('--zeno-accent-gradient')
    expect(styles).not.toContain('linear-gradient')
    expect(styles).not.toContain('radial-gradient')
  })
})

describe('visual weight polish', () => {
  it('avoids heavy UI font weights in the Nezha-like shell', () => {
    expect(styles).not.toContain('font-weight: 650')
    expect(styles).not.toContain('font-weight: 700')
    expect(styles).not.toContain('font-weight: 750')
    expect(styles).not.toContain('font-weight: 760')
    expect(styles).not.toContain('font-weight: 780')
  })

  it('keeps custom icon strokes and resource curves lighter than the default heavy Lucide stroke', () => {
    expect(styles).toContain('stroke-width: 1.75')
    expect(styles).toContain('.detail-title-button svg')
    expect(styles).toContain('stroke-width: 1.6')
    expect(styles).toContain('.resource-chart-line { fill: none; stroke-width: 1.55')
  })
})
